home/urls.py
from django.conf.urls import url
from . import views 
app_name = 'home'
urlpatterns = [
    url(r'^$', views.home,name="index"),
    url(r'^tolaram/menu/$', views.menu,name="menu"),
    url(r'^tolaram/blog/$', views.blog,name="blog"),
    url(r'^tolaram/contact/$', views.contact,name="contact"),
    url(r'^tolaram/events/$', views.events,name="events"),
    url(r'^tolaram/menu/(?P<id>\d+)/$', views.variety,name="variety"),

]

tolaramsweets/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    url('^admin/',admin.site.urls),
    url('^', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

class Item(models.Model):
    ctg_name=models.CharField(max_length=250)
    img=models.ImageField(blank=True,upload_to='item')

    def __str__(self):
        return str(self.ctg_name)

class Products(models.Model):
    item_id=models.ForeignKey(Item,on_delete=models.CASCADE)
    cost=models.CharField(max_length=100)
    name=models.CharField(max_length=250)
    desc=models.TextField()
    best_seller=models.BooleanField(default=0)
    img=models.ImageField(blank=True,upload_to='products')

    def __str__(self):
        return str(self.name)            

class FestivePack(models.Model):
    cost=models.IntegerField(default=0)
    name=models.CharField(max_length=500)
    desc=models.TextField()
    img=models.ImageField(blank=True,upload_to='FestivePack')

class Review(models.Model):
    pid=models.ForeignKey(Products,on_delete=models.CASCADE)
    rating=models.CharField(max_length=10,default="0")
    name=models.CharField(max_length=250)
    subject=models.TextField(default="")
    desc=models.TextField()
    email=models.CharField(max_length=250,blank=True    )

home/views.py
from django.shortcuts import render
from home.models import Item,Products

def home(request):
	best_sellers=Products.objects.filter(best_seller=1)
	print(best_sellers)
	return render(request, 'home/index.html',{"bests":best_sellers})

def variety(request,id=1):
	all_products=Products.objects.filter(item_id=int(id))
	return render(request, 'home/variety.html',{"products":all_products})

def menu(request):
	all_ctg=Item.objects.all()
	return render(request, 'home/menu.html',{"categories":all_ctg})

def blog(request):
	return render(request, 'home/blog.html')


def contact(request):
	return render(request, 'home/contact.html')


def events(request):
	return render(request, 'home/events.html')

home/templates/home/contact.html
<!--A Design by W3layouts 
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	{% load static %}
<title>THE HOUSE OF SWEETS TOLARAM SWEETS</title>
<link href={% static "home/css/bootstrap.css" %} rel="stylesheet" type="text/css" media="all" />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src={% static "home/js/jquery.min.js" %}></script>
<!-- Custom Theme files -->
<!--theme-style-->
<link href={% static "home/css/style.css" %} rel="stylesheet" type="text/css" media="all" />	
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Cookery Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!---->
<link href='//fonts.googleapis.com/css?family=Raleway:400,200,100,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,700' rel='stylesheet' type='text/css'>
<link href={% static "home/css/styles.css" %} rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/component.css" />
	<!-- animation-effect -->
<link href={% static "home/css/animate.min.css" rel="stylesheet"> 
<script src={% static "home/js/wow.min.js" %}></script>
<script>
 new WOW().init();
</script>
<!-- //animation-effect -->

</head>
<body>
<div class="header head">
	<div class="container">
		<div class="logo">
			<h1><a href="index.html"><span></span><img src={% static "home/images/oo.png" %} alt=""><img src={% static "home/images/oo.png" %} alt="">TOLARAM SWEETS</a></h1>
		</div>
		<div class="nav-icon">		
			<a href="#" class="navicon"></a>
				<div class="toggle">
					<ul class="toggle-menu">
						<li><a  href="{% url 'home:index' %}">HOME</a></li>
						<li><a  href="/tolaram/menu">MENU</a></li>
						<li><a  href="/tolaram/blog">BOOK ORDERS</a></li>
						<li><a  href="/tolaram/typo">FESTIVE OFFERS</a></li>
						<li><a  href="/tolaram/events">FEEDBACK</a></li>
						<li><a class="active" href="/tolaram/contact">ABOUT US</a></li>
					</ul>
				</div>
			<script>
			$('.navicon').on('click', function (e) {
			  e.preventDefault();
			  $(this).toggleClass('navicon--active');
			  $('.toggle').toggleClass('toggle--active');
			});
			</script>
		</div>
	<div class="clearfix"></div>
	</div>
	<!-- start search-->	
		
</div>
<!--content-->
	<div class="contact">
		<div class="container">
		<div class="menu-top">
				<div class="col-md-4 menu-left animated wow fadeInLeft" data-wow-duration="1000ms" data-wow-delay="500ms">
					<h3>Contact</h3>
					<label><i class="glyphicon glyphicon-menu-up"></i></label>
					<span>TOLARAM SWEETS</span>
				</div>
				<div class="col-md-8 menu-right animated wow fadeInRight" data-wow-duration="1000ms" data-wow-delay="500ms">
					<p><font size='6'>FOR CONTACT PLEASE FILL THE FORM!!</font></p>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="contact-top">
			<div class="col-md-5 contact-map">
			<h5>Google Map</h5>
			<div class="map animated wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d37494223.23909492!2d103!3d55!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x453c569a896724fb%3A0x1409fdf86611f613!2sRussia!5e0!3m2!1sen!2sin!4v1415776049771"></iframe>

			</div>
			<div class="address">
					      <h4>Address</h4>
					      <p> TOLARAM SWEETS</p>
						  <p>BADA LASHKAR GWALIOR </p>
						  <p>ph : 0751-242994</p>
						  <p>Email : <a href="mailto:example@gmail.com">tolarmsweets@gmail.com</a></p>
					 </div>
			</div>
			<div class="col-md-7 contact-para animated wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="500ms">
			<h5>Contact Form</h5>
			<form>
				<div class="grid-contact">
					<div class="col-md-6 contact-grid">
						<p class="your-para">Name </p>
							<input type="text" value="" onfocus="this.value='';" onblur="if (this.value == '') {this.value ='';}">
						</div>
					<div class="col-md-6 contact-grid">
					<p class="your-para">Phone number</p>	
						<input type="text" value="" onfocus="this.value='';" onblur="if (this.value == '') {this.value ='';}">
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="grid-contact">
					<div class="col-md-6 contact-grid">
						<p class="your-para">Email</p>
						<input type="text" value="" onfocus="this.value='';" onblur="if (this.value == '') {this.value ='';}">
					</div>
					<div class="col-md-6 contact-grid">
						<p class="your-para">Password</p>
						<input type="Password" value="" onfocus="this.value='';" onblur="if (this.value == '') {this.value ='';}">
					</div>
					<div class="clearfix"> </div>
				</div>
				<p class="your-para msg-para">MESSAGE</p>
				<textarea cols="77" rows="6" value=" " onfocus="this.value='';" onblur="if (this.value == '') {this.value = '';}"></textarea>
					<div class="send">
						<input type="submit" value="Send " >
					</div>
			</form>
			</div>	
			
			<div class="clearfix"> </div>
		</div>
	</div>
	</div>
<!--footer-->
	<div class="footer">
		<div class="container">
			<div class="footer-head">
				<div class="col-md-8 footer-top animated wow fadeInRight" data-wow-duration="1000ms" data-wow-delay="500ms">
					<ul class=" in">
						<li><a href="index.html">Home</a></li>
						<li><a  href="menu.html">Menu</a></li>
						<li><a  href="events.html">FEEDBACK</a></li>
						<li><a  href="contact.html">ABOUT US</a></li>
					</ul>					
						<span>HOUSE OF DELICIOUS SWEETS</span>
				</div>
				<div class="col-md-4 footer-bottom  animated wow fadeInLeft" data-wow-duration="1000ms" data-wow-delay="500ms">
					<h2>TOLRAM SWEETS</h2>
					<label><i class="glyphicon glyphicon-menu-up"></i></label>
					<p>NEAR GOVT.PRESS BADA,LASHKAR GWALIOR(M.P.)...</p>
					<ul class="social-ic">
						<li><a href="#"><i></i></a></li>
						<li><a href="#"><i class="ic"></i></a></li>
						<li><a href="#"><i class="ic1"></i></a></li>
						<li><a href="#"><i class="ic2"></i></a></li>
						<li><a href="#"><i class="ic3"></i></a></li>
					</ul>

				</div>
			<div class="clearfix"> </div>
					
			</div>
			<p class="footer-class animated wow bounce" data-wow-duration="1000ms" data-wow-delay="500ms">&copy;2018 TOLARAM SWEETS   <a href= target="_blank">TOLARAM SWEETS</a> </p>
		</div>
	</div>		
	<!--//footer-->

</body>
</html>

home/templates/home/events.html
<!--A Design by W3layouts 
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	{% load static %}
<title>THE HOUSE OF SWEETS TOLARAM SWEETS</title>
<link href={% static "home/css/bootstrap.css" %} rel="stylesheet" type="text/css" media="all" />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src={% static "home/js/jquery.min.js" %}></script>
<!-- Custom Theme files -->
<!--theme-style-->
<link href={% static "home/css/style.css" %} rel="stylesheet" type="text/css" media="all" />	
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Cookery Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!---->
<link href='//fonts.googleapis.com/css?family=Raleway:400,200,100,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,700' rel='stylesheet' type='text/css'>
<link href={% static "home/css/styles.css" %} rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/component.css" />
	<!-- animation-effect -->
<link href={% static "homecss/animate.min.css" %} rel="stylesheet"> 
<script src={% static "home/js/wow.min.js" %}></script>
<script>
 new WOW().init();
</script>
<!-- //animation-effect -->

</head>
<body>
<div class="header head">
	<div class="container">
		<div class="logo animated wow pulse" data-wow-duration="1000ms" data-wow-delay="500ms">
			<h1><a href="index.html"><span></span><img src={% static "home/images/oo.png" %} alt=""><img src={% static "home/images/oo.png" %} alt="">TOLARAM SWEETS</a></h1>
		</div>
		<div class="nav-icon">		
			<a href="#" class="navicon"></a>
				<div class="toggle">
					<ul class="toggle-menu">
						<li><a  href="{% url 'home:index' %}">Home</a></li>
						<li><a  href="/tolaram/menu">MENU</a></li>
						<li><a  href="/tolaram/blog">BOOK ORDERS</a></li>
						<li><a  href="/tolaram/typo">FESTIVE OFFERS</a></li>
						<li><a class="active" href="/tolaram/events">FEEDBACK</a></li>
						<li><a  href="/tolaram/contact">ABOUT US</a></li>
					</ul>
				</div>
			<script>
			$('.navicon').on('click', function (e) {
			  e.preventDefault();
			  $(this).toggleClass('navicon--active');
			  $('.toggle').toggleClass('toggle--active');
			});
			</script>
		</div>
	<div class="clearfix"></div>
	</div>
	<!-- start search-->	
		
</div>
<!--content-->
<div class="content">
	<div class="events">
		<div class="container">
			<div class="events-top">
				<div class="col-md-4 events-left animated wow fadeInLeft" data-wow-duration="1000ms" data-wow-delay="500ms">
					<h3>FEEDBACK</h3>
					<label><i class="glyphicon glyphicon-menu-up"></i></label>
					<span>FOR CUSTOMER SATISFACTION</span>
				</div>
				<div class="col-md-8 events-right animated wow fadeInRight" data-wow-duration="1000ms" data-wow-delay="500ms">
					<p>PLEASE LET US KNOW YOUR EXPERIENCE WITH TOLRAM SWEETS.</p>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="events-bottom">
				<div class="col-md-5 events-bottom1 animated wow fadeInRight" data-wow-duration="1000ms" data-wow-delay="500ms">
					<a href="single.html"><img src={% static "home/images/ev.jpg" %} alt="" class="img-responsive"></a>
				</div>
				<div class="col-md-7 events-bottom2 animated wow fadeInLeft" data-wow-duration="1000ms" data-wow-delay="500ms">
					<h3>INDIAN SWEETS</h3>
					<label><i class="glyphicon glyphicon-menu-up"></i></label>
					<p>When it comes to selecting an Indian restaurant, most people choose the spot that creates the best chicken tikka masala or palak paneer. Dessert is often an afterthought and the less knowledgeable diner might just stick with the basics, from the ubiquitous Indian donut hole, known as gulab jamun, to the spongy ricotta cheese balls, rasgulla.

But diners with a sweet tooth should consider a variety of other options, including Indian ice cream kulfi, sweetened yogurt srikhand and carrot halwa. The dairy averse can opt for unique choices like Indian bread pudding at Passage to India or apricot compote offered at Masala Art.
					</p>
					<div class="read-more">						
						<a class="link link-yaku" href="single.html">
							<span>R</span><span>e</span><span>a</span><span>d</span> <span>M</span><span>o</span><span>r</span><span>e</span>					
						</a>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="events-bottom">
				<div class="col-md-7 events-bottom2 animated wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
					<h3>INDIAN NAMKEENS</h3>
					<label><i class="glyphicon glyphicon-menu-up"></i></label>
					<p>We have all types of south indian namkeen at very reasonalble prices. . 
we offer best quality products to our customers and also very good after sale services. . . . 
there are many variety of namkeens like south mixture, punjabi mixture, chakli, banana chips, murku and also south indian biscuits.
					</p>
					<div class="read-more">						
						<a class="link link-yaku" href="single.html">
							<span>R</span><span>e</span><span>a</span><span>d</span> <span>M</span><span>o</span><span>r</span><span>e</span>					
						</a>
					</div>
				</div>
				<div class="col-md-5 events-bottom1 animated wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="500ms">
					<a href="single.html"><img src={% static "home/images/ev1.jpg" %} alt="" class="img-responsive"></a>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="events-bottom">
				<div class="col-md-5 events-bottom1 animated wow fadeInLeft" data-wow-duration="1000ms" data-wow-delay="500ms">
					<a href="single.html"><img src={% static "home/images/ev2.jpg" %} alt="" class="img-responsive"></a>
				</div>
				<div class="col-md-7 events-bottom2 animated wow fadeInRight" data-wow-duration="1000ms" data-wow-delay="500ms">
					<h3>DRY FRUITS SWEETS</h3>
					<label><i class="glyphicon glyphicon-menu-up"></i></label>
					<p>DRY FRUIT BARFI: It might also be listed as burfee, barfi or barfee, but regardless of the spelling, diners can expect to dig into dense milk fudge, typically mixed with cashews, almond and other nuts.While it’s more commonly found in Indian grocery stores than restaurants, Masala Art at Southwest Waterfront serves a doda burfi made with wheat flour while Jaipur Royal Indian Cuisine in Fairfax serves a coconut burfi.
					</p>
					<div class="read-more">						
						<a class="link link-yaku" href="single.html">
							<span>R</span><span>e</span><span>a</span><span>d</span> <span>M</span><span>o</span><span>r</span><span>e</span>					
						</a>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="events-bottom">
				<div class="col-md-7 events-bottom2 animated wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="500ms">
					<h3>BENGALI SWEETS</h3>
					<label><i class="glyphicon glyphicon-menu-up"></i></label>
					<p>Rasmalai: Cottage cheese balls swimming in sweetened milk made an appearance on many Indian menus, including DuPont Circle’s Le Mirch, Jyoti Indian Cuisine and Taj of India in Georgetown.

Rabri: Consisting of thickened, sweetened milk that is boiled for hours, the labor- and time-intensive dessert is a rare find on an Indian dessert menu. Fans of the sweet dish can order it at Bombay Club, where it’s topped with blueberries. Diners traveling near Baltimore can also order it at Sneha Indian Cuisine in Catonsville, whose kitchen is led by Rasika and Bombay Club alums Zamin Mohammed and Pan Singh.


					</p>
					<div class="read-more">						
						<a class="link link-yaku" href="single.html">
							<span>R</span><span>e</span><span>a</span><span>d</span> <span>M</span><span>o</span><span>r</span><span>e</span>					
						</a>
					</div>
				</div>
				<div class="col-md-5 events-bottom1 animated wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
					<a href="single.html"><img src={% static "home/images/ev3.jpg" %} alt="" class="img-responsive"></a>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
</div>

<!--footer-->
	<div class="footer">
		<div class="container">
			<div class="footer-head">
				<div class="col-md-8 footer-top animated wow fadeInRight" data-wow-duration="1000ms" data-wow-delay="500ms">
					<ul class=" in">
						<li><a href="index.html">Home</a></li>
						<li><a  href="menu.html">Menu</a></li>
						<li><a  href="events.html">FEEDBACK</a></li>
						<li><a  href="contact.html">ABOUT US</a></li>
					</ul>					
						<span>HOUSE OF DELICIOUS SWEETS</span>
				</div>
				<div class="col-md-4 footer-bottom  animated wow fadeInLeft" data-wow-duration="1000ms" data-wow-delay="500ms">
					<h2>TOLARAM SWEETS</h2>
					<label><i class="glyphicon glyphicon-menu-up"></i></label>
					<p>NEAR GOVT.PRESS BADA,LASHKAR GWALIOR(M.P.)..</p>
					<ul class="social-ic">
						<li><a href="#"><i></i></a></li>
						<li><a href="#"><i class="ic"></i></a></li>
						<li><a href="#"><i class="ic1"></i></a></li>
						<li><a href="#"><i class="ic2"></i></a></li>
						<li><a href="#"><i class="ic3"></i></a></li>
					</ul>

				</div>
			<div class="clearfix"> </div>
					
			</div>
			<p class="footer-class animated wow bounce" data-wow-duration="1000ms" data-wow-delay="500ms">&copy; 2018 TOLARAM SWEETS <a href="http://w3layouts.com/" target="_blank"></a> </p>
		</div>
	</div>			
	<!--//footer-->



</body>
</html>

home/templates/home/menu.html
<!--A Design by W3layouts 
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	{% load static %}
<title>THE HOUSE OF SWEETS TOLARAM SWEETS  | Menu :: TOLARAM SWEETS</title>
<link href={% static "home/css/bootstrap.css" %} rel="stylesheet" type="text/css" media="all" />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src={% static "home/js/jquery.min.js" %}></script>
<!-- Custom Theme files -->
<!--theme-style-->
<link href={% static "home/css/style.css" %} rel="stylesheet" type="text/css" media="all" />	
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Cookery Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!---->
<link href='//fonts.googleapis.com/css?family=Raleway:400,200,100,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,700' rel='stylesheet' type='text/css'>
<link href={% static "home/css/styles.css" %} rel="stylesheet">
<!-- animation-effect -->
<link href={% static "home/css/animate.min.css" %} rel="stylesheet"> 
<script src={% static "home/js/wow.min.js" %}></script>
<script>
 new WOW().init();
</script>
<button type="button" class="btn btn-default" aria-label="Left Align">
  <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
</button>

<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-" aria-hidden="true"></span> Star
</button




<!-- //animation-effect -->

</head>
<body>
<div class="header head">
	<div class="container">
		<div class="logo animated wow pulse" data-wow-duration="1000ms" data-wow-delay="500ms">
			<h1><a href="index.html"><span></span><img src={% static "home/images/oo.png" %} alt=""><img src={% static "home/images/oo.png" %} alt="">TOLARAM SWEETS MENU</a></h1>
		</div>
		<div class="nav-icon">		
			<a href="#" class="navicon"></a>
				<div class="toggle">
					<ul class="toggle-menu">
						<li><a  href="{% url 'home:index' %}">Home</a></li>
						<li><a class="active" href="/tolaram/menu">MENU</a></li>
						<li><a  href="/tolaram/blog">BOOK ORDERS</a></li>
						<li><a  href="/tolaram/typo">FESTIVE OFFERS</a></li>	
						<li><a  href="/tolaram/events">FEEDBACK</a></li>
						<li><a  href="/tolaram/contact">ABOUT US</a></li>
					</ul>
				</div>
			<script>
			$('.navicon').on('click', function (e) {
			  e.preventDefault();
			  $(this).toggleClass('navicon--active');
			  $('.toggle').toggleClass('toggle--active');
			});
			</script>
		</div>
	<div class="clearfix"></div>
	</div>
	<!-- start search-->	
		
</div>
<!--content-->
	<div class="menu">
		<div class="container">
			<div class="menu-top">
				<div class="col-md-4 menu-left animated wow fadeInLeft" data-wow-duration="1000ms" data-wow-delay="500ms">
					<h3>Menu</h3>
					<label><i class="glyphicon glyphicon-menu-up"></i></label>
					<span>There are many variations</span>
				</div>
				<div class="col-md-8 menu-right animated wow fadeInRight" data-wow-duration="1000ms" data-wow-delay="500ms">
					<p>Barfi is very popular traditional sweets not just in India but in the entire Indian subcontinent. There are several variety of it but the plain Barfi is the one which is made of milk which is then cooked with sugar in a large pan until it becomes a solid mass. This solid mass can be cut into a rhombus or rectangular shape from thin to thick thickness (though you can make any shape you want).  Some of the famous varieties of Barfi are बेसन की बर्फी (Besan ki Barfi, which is made with gram flour), काजू की बर्फी (Kaaju ki Barfi, which is made with cashews), पिस्ते की बर्फी (Piste ki Barfi, which is made with ground pistachios), चोकलेट की बर्फी (Chocolate ki Barfi, which is made with chocolate).</p>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="menu-bottom animated wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
				{% for category in categories %}
				<div class="col-md-4 menu-bottom1" style="margin-bottom: 30px;">
					<div class="btm-right">
						<a href={{ category.pk }}/>
							<img src={{ category.img.url }} alt="" class="img-responsive" style="width:400px;height:300px; : ">
							<div class="captn">
								<h4>{{ category.ctg_name }}</h4>				
							</div>
						</a>						
					</div>
				</div>
				{% endfor %}
				<div class="clearfix"> </div>				
			</div>
		</div>
	</div>
<!--footer-->
	<div class="footer">
		<div class="container">
			<div class="footer-head">
				<div class="col-md-8 footer-top animated wow fadeInRight" data-wow-duration="1000ms" data-wow-delay="500ms">
					<ul class=" in">
						<li><a href="index.html">HOME</a></li>
						<li><a  href="menu.html">MENU</a></li>
						
						
						<li><a  href="events.html">FEEDBACK</a></li>
						<li><a  href="contact.html">ABOUT US</a></li>
					</ul>					
						<span>HOUSE OF DELICIOUS SWEETS</span>
				</div>
				<div class="col-md-4 footer-bottom  animated wow fadeInLeft" data-wow-duration="1000ms" data-wow-delay="500ms">
					<h2>TOLARAM SWEETS</h2>
					<label><i class="glyphicon glyphicon-menu-up"></i></label>
					<p>NEAR GOVT.PRESS BADA,LASHKAR GWALIOR(M.P.).</p>
					<ul class="social-ic">
						<li><a href="#"><i></i></a></li>
						<li><a href="#"><i class="ic"></i></a></li>
						<li><a href="#"><i class="ic1"></i></a></li>
						<li><a href="#"><i class="ic2"></i></a></li>
						<li><a href="#"><i class="ic3"></i></a></li>
					</ul>

				</div>
			<div class="clearfix"> </div>
					
			</div>
			<p class="footer-class animated wow bounce" data-wow-duration="1000ms" data-wow-delay="500ms">&copy; &copy; 2018 TOLARAM SWEETS </p>
		</div>
	</div>		
	<!--//footer-->

</body>
</html>